--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/TpaACM
build-by-default: true
branches:
- main
projects:
  TpaACM:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
