name: TpaACM
version: 1.1
main: fernanACM\Tpa
api: 3.0.0
author: fernanACM
website: https://github.com/fernanACM
description: A simple TPA for PocketMine-MP

commands: 
  tpa:
    description: Send teleport request to teleport you to player 
  tpahere:
    description: Send teleport request to teleport player to your self
  tpaccept:
    description: Accept teleport request
  tpadeny:
    description: Deny teleport request
  
