name: TpaACM
version: 1.0
main: Tp\Tpa
api: 3.0.0
author: fernanACM
website: https://github.com/fernanACM
description: Simple tpa v1.0

commands: 
  tpa:
    description: Send teleport request to teleport you to player 
  tpahere:
    description: Send teleport request to teleport player to your self
  tpaccept:
    description: Accept teleport request
  tpadeny:
    description: Deny teleport request
  
